version: 0.1.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2019
  - macos
  - Ubuntu2004

stack: node 16

init:
  - git config --global core.autocrlf input
  - sh: |
      if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu2004" ]
      then
        sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
        sudo apt-get install snapd
        sudo snap install snapcraft --classic
        sudo apt-get install -y rpm
      fi
      if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Visual Studio 2019" ]
      then
        install --global windows-build-tools
        npm config set python "C:\Python27\python.exe"
      fi

install:
  - git reset --hard HEAD
  - node --version
  - yarn

build_script:
  - yarn release

test: off
