version: 0.1.{build}

branches:
  only:
    - master

image:
  - macOS
  - Ubuntu2004

stack: node 14

init:
  - git config --global core.autocrlf input
  - sh: |
      if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "macOS" ]
      then
        python --version
        brew install python3
        brew link --overwrite python@3.8
        python --version
      fi

install:
  - git reset --hard HEAD
  - npm install node-sass@4.14.1
  - node --version
  - npm install

build_script:
  - npm run release

test: off
