name: Download and Upload Release Files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download release files
        run: |
          mkdir release_files
          cd release_files
          curl -LJO https://github.com/${{ github.repository }}/archive/${{ github.ref }}/tar.gz
          tar -xzf *.tar.gz --strip-components=1
          rm *.tar.gz

      - name: Install B2 CLI
        run: |
          curl https://f000.backblazeb2.com/file/backblazeb2-public/b2-linux-x86_64 -o b2
          chmod +x b2

      - name: Create or update folder in Backblaze
        run: |
          ./b2 authorize-account ${{ secrets.B2_ACCOUNT_ID }} ${{ secrets.B2_APPLICATION_KEY }}
          ./b2 create-bucket ${{ secrets.B2_BUCKET_NAME }} ${{ github.ref }} allPublic

      - name: Upload release files to Backblaze
        run: |
          ./b2 authorize-account ${{ secrets.B2_ACCOUNT_ID }} ${{ secrets.B2_APPLICATION_KEY }}
          ./b2 sync --delete --excludeRegex ".*\.git.*" release_files/ ${{ secrets.B2_BUCKET_NAME }}/${{ github.ref }}
