name: Download and Upload Release Files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release
        id: latest_release
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}

      - name: Download all assets from latest release
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            repo: ${{ github.repository }}
            version: tags/${{ steps.latest_release.outputs.tag_name }}
            file: "*"
            target: release-assets/
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install B2 CLI
        run: |
          curl https://f000.backblazeb2.com/file/backblazeb2-public/b2-linux-x86_64 -o b2
          chmod +x b2

      - name: Create or update folder in Backblaze
        run: |
          ./b2 authorize-account ${{ secrets.B2_ACCOUNT_ID }} ${{ secrets.B2_APPLICATION_KEY }}
          ./b2 create-bucket ${{ secrets.B2_BUCKET_NAME }} ${{ github.ref }} allPublic

      - name: Upload release files to Backblaze
        run: |
          ./b2 authorize-account ${{ secrets.B2_ACCOUNT_ID }} ${{ secrets.B2_APPLICATION_KEY }}
          ./b2 sync --delete --excludeRegex ".*\.git.*" release-assets/ ${{ secrets.B2_BUCKET_NAME }}/${{ github.ref }}
