name: Download and Upload Release Files

on:
  push:
    branches: [master]
    tags:
      # Build on every tag in the form v1.2.3-something.4
      - "v*"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run custom script
        run: |
          wget https://github.com/koodo-reader/koodo-reader/tree/master/src/upload.sh
          chmod +x ./upload.sh
          ./upload.sh ${{ secrets.B2_ACCOUNT_ID }} ${{ secrets.B2_APPLICATION_KEY }}
